using System;
using System.Collections.Generic;
using EdApp.AutoFill.BL.Contract.Services;
using EdApp.AutoFill.BL.Model;

namespace EdApp.AutoFill.BL.Service;

/// <inheritdoc cref="IJsonNodeService"/>>
public class JsonNodeService : IJsonNodeService
{
    private readonly IJsonLineService _jsonLineService;

    public JsonNodeService(IJsonLineService jsonLineService)
    {
        _jsonLineService = jsonLineService;
    }

    public IEnumerable<JsonNode> GetJsonNodes()
    {
        return GetAllJsonNodes();
    }

    public string GetJson(IEnumerable<JsonNode> jsonNodes)
    {
        return string.Join(Environment.NewLine, jsonNodes);
    }

    public void UpdateNodeValue(IEnumerable<JsonNode> jsonNodes, string jsonNodePath, string attributeName, string value)
    {
        var jsonNode = GetJsonNode(jsonNodes, jsonNodePath, attributeName);
        var updatedLineValue = UpdateLine(jsonNode.Line,  value);
        jsonNode.Line = updatedLineValue;
    }

    private string UpdateLine(string currentLineValue, string value)
    {
        return _jsonLineService.UpdateValue(currentLineValue, value);
    }

    private JsonNode GetJsonNode(IEnumerable<JsonNode> jsonNodes, string jsonNodePath, string attributeName)
    {
        throw new NotImplementedException();
    }

    public IEnumerable<JsonNode> GetAllJsonNodes()
    {
        var jsonNodes = new List<JsonNode>();
        jsonNodes.Add(new JsonNode { Number = 1, NodeFullPath = "root", Line = "{\"BaseCalculation\": {", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 2, NodeFullPath = "BaseCalculation", Line = "    \"tra\": {", IsNode = false, Comment = "Tra", Depth = 2 });
        jsonNodes.Add(new JsonNode { Number = 3, NodeFullPath = "Tra", Line = "        \"id\": 171419,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 4, NodeFullPath = "Tra", Line = "        \"version\": 2,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 5, NodeFullPath = "Tra", Line = "        \"kindOfMachine\": \"K\",", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 6, NodeFullPath = "Tra", Line = "        \"motorSeries\": \"SIMOTICS HV C\",", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 7, NodeFullPath = "Tra", Line = "        \"mlfb1\": \"1NB1\",", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 8, NodeFullPath = "Tra", Line = "        \"mlfb2\": \"458\",", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 9, NodeFullPath = "Tra", Line = "        \"mlfb3\": \"4\",", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 10, NodeFullPath = "Tra", Line = "        \"kindOfRtr\": \"KL\",", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 11, NodeFullPath = "Tra", Line = "        \"username\": \"STÖGER, JOSE\",", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 12, NodeFullPath = "Tra", Line = "        \"tokenOriginator\": \"STO\",", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 13, NodeFullPath = "Tra", Line = "        \"tokenRevisor\": \"EV\",", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 14, NodeFullPath = "Tra", Line = "        \"date\": \"2018-10-17T00:00:00\",", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 15, NodeFullPath = "Tra", Line = "        \"bgStatorWinding1Id\": 171419,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 16, NodeFullPath = "Tra", Line = "        \"bgStatorWinding1Version\": 1,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 17, NodeFullPath = "Tra", Line = "        \"bgRotorCageId\": 151855,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 18, NodeFullPath = "Tra", Line = "        \"bgRotorCageVersion\": 0,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 19, NodeFullPath = "Tra", Line = "        \"bgStatorSheetId\": 145201,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 20, NodeFullPath = "Tra", Line = "        \"bgStatorSheetVersion\": 2,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 21, NodeFullPath = "Tra", Line = "        \"bgRotorSheetId\": 152289,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 22, NodeFullPath = "Tra", Line = "        \"bgRotorSheetVersion\": 0,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 23, NodeFullPath = "Tra", Line = "        \"comment\": null,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 24, NodeFullPath = "Tra", Line = "        \"isLastVersion\": true,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 25, NodeFullPath = "Tra", Line = "        \"creationTime\": null,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 26, NodeFullPath = "Tra", Line = "        \"creatorId\": null,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 27, NodeFullPath = "Tra", Line = "        \"lastModificationTime\": null,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 28, NodeFullPath = "Tra", Line = "        \"lastModifierId\": null,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 29, NodeFullPath = "Tra", Line = "        \"bgStatorSheet\": {", IsNode = false, Comment = "Tra", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 30, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"windingSlotId\": 1012,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 31, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"windingSlotDesign\": \"NJA\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 32, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"windingSlotsNo\": 48,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 33, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"material\": \"M470P65A\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 34, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"coreSectionLength\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 35, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"leakageSlotH\": 4.5,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 36, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"endPlate\": 6,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 37, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"coolingSlotId\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 38, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"coolingSlotDesign\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 39, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"coolingSlotsNo\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 40, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"diamOuter\": 620,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 41, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"diamInner\": 370,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 42, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"coreLengthIron\": 708,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 43, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"coreLengthTotal\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 44, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"airVentsNo\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 45, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"diamPitchCircle\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 46, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"stackingFactor\": 0.96,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 47, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"backlackEndPlate\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 48, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"windingSlot\": {", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 49, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"id\": 1012,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 50, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"design\": \"NJA\",", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 51, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"w1\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 52, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"w2\": 13.5,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 53, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"h1\": 62,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 54, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"h2\": 2.4,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 55, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"w3\": 13.9,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 56, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"w4\": 14.3,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 57, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"w5\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 58, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"w6\": 14.3,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 59, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"h3\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 60, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"h4\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 61, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"h5\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 62, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"diam1\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 63, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"w7\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 64, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"diam2\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 65, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"h6\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 66, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"radius1\": 0.6,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 67, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"radius2\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 68, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"angle1\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 69, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"h7\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 70, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"angle2\": 2.473,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 71, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"radius3\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 72, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"maxLeakageSlot\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 73, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"punchingDiam\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 74, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"punchingAirGap\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 75, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"slotsNo\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 76, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"punchingToolType\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 77, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"status\": null", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 78, NodeFullPath = "Tra.BgStatorSheet", Line = "            },", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 79, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"coolingSlot\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 80, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"id\": 145201,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 81, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"version\": 2,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 82, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"isLastVersion\": true,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 83, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"standardComments\": [],", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 84, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"date\": \"2021-06-17T00:00:00\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 85, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"daisiUseable\": true,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 86, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"username\": \"SYSTEM-IMPORT\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 87, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"comment\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 88, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"standardText\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 89, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"status\": \"Released\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 90, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"creationTime\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 91, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"creatorId\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 92, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"lastModificationTime\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 93, NodeFullPath = "Tra.BgStatorSheet", Line = "            \"lastModifierId\": null", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 94, NodeFullPath = "Tra", Line = "        },", IsNode = false, Comment = "", Depth = 2 });
        jsonNodes.Add(new JsonNode { Number = 95, NodeFullPath = "Tra", Line = "        \"bgRotorSheet\": {", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 96, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"windingSlotsNo\": 38,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 97, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"windingSlotId\": 1262,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 98, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"airGab\": 2.0,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 99, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"windingSlotDesign\": \"NRA\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 100, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"material\": \"M470P65A\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 101, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"coreSectionLength\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 102, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"leakageSlotH\": 4,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 103, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"leakageSlotHDiff\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 104, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"imdSheetSlotId\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 105, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"imdSheetSlotDesign\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 106, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"imdSheetSlotNo\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 107, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"imdSheetLeakageSlotH\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 108, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"coolingSlotsNo\": 36,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 109, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"coolingSlotId\": 1009,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 110, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"coolingSlotDesign\": \"NAT\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 111, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"coolingSlotCustomId\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 112, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"diamOuter\": 366,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 113, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"diamInner\": 140,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 114, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"coreLengthIron\": 708,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 115, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"coreLengthTotal\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 116, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"airVentsNo\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 117, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"diamPitchCircle\": 241,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 118, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"stackingFactor\": 0.96,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 119, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"endPlate\": 6,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 120, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"spiderShaft\": false,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 121, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"skewAxialMm\": 0,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 122, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"skewAxialDegMin\": \"0  0\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 123, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"backlackEndPlate\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 124, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"coolingSlot\": {", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 125, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"id\": 1009,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 126, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"design\": \"NAT\",", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 127, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"w1\": 12.5,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 128, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"w2\": 8,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 129, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"h1\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 130, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"h2\": 32,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 131, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"w3\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 132, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"w4\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 133, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"w5\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 134, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"w6\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 135, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"h3\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 136, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"h4\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 137, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"h5\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 138, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"diam1\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 139, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"w7\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 140, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"diam2\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 141, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"h6\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 142, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"radius1\": 2.5,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 143, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"radius2\": 2.5,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 144, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"angle1\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 145, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"h7\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 146, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"angle2\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 147, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"radius3\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 148, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"maxLeakageSlot\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 149, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"punchingDiam\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 150, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"punchingAirGap\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 151, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"slotsNo\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 152, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"punchingToolType\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 153, NodeFullPath = "Tra.BgStatorSheet.CoolingSlot", Line = "                \"status\": null", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 154, NodeFullPath = "Tra.BgRotorSheet", Line = "            },", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 155, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"imdSheetSlot\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 156, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"windingSlot\": {", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 157, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"id\": 1262,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 158, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"design\": \"NRA\",", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 159, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"w1\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 160, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"w2\": 11.7,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 161, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"h1\": 32.6,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 162, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"h2\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 163, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"w3\": 5,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 164, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"w4\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 165, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"w5\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 166, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"w6\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 167, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"h3\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 168, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"h4\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 169, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"h5\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 170, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"diam1\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 171, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"w7\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 172, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"diam2\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 173, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"h6\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 174, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"radius1\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 175, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"radius2\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 176, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"angle1\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 177, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"h7\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 178, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"angle2\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 179, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"radius3\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 180, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"maxLeakageSlot\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 181, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"punchingDiam\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 182, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"punchingAirGap\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 183, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"slotsNo\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 184, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"punchingToolType\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 185, NodeFullPath = "Tra.BgStatorSheet.WindingSlot", Line = "                \"status\": null", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 186, NodeFullPath = "Tra.BgRotorSheet", Line = "            },", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 187, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"id\": 152289,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 188, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"version\": 0,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 189, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"isLastVersion\": true,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 190, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"standardComments\": [],", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 191, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"date\": \"2021-06-17T00:00:00\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 192, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"daisiUseable\": true,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 193, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"username\": \"SYSTEM-IMPORT\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 194, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"comment\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 195, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"standardText\": \"C19:@@;\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 196, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"status\": \"Released\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 197, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"creationTime\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 198, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"creatorId\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 199, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"lastModificationTime\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 200, NodeFullPath = "Tra.BgRotorSheet", Line = "            \"lastModifierId\": null", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 201, NodeFullPath = "Tra", Line = "        },", IsNode = false, Comment = "", Depth = 2 });
        jsonNodes.Add(new JsonNode { Number = 202, NodeFullPath = "Tra", Line = "        \"bgStatorWinding1\": {", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 203, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"type\": \"Z\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 204, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"label\": \"W\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 205, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"conductorsSlotNo\": \"5+6\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 206, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wire1ParallelNo\": 1,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 207, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wire2ParallelNo\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 208, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wire1UnisolatedDiam\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 209, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wire1IsolatedDiam\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 210, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wire1UnisolatedCs\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 211, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wireUnisolatedW\": 10,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 212, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wireUnisolatedH\": 2.5,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 213, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wireIsolatedW\": 10.4,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 214, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wireIsolatedH\": 2.9,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 215, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"overhangLength\": 540,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 216, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wire1CopperWeight\": 235,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 217, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wire2CopperWeight\": 0,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 218, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wire2UnisolatedDiam\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 219, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wire2IsolatedDiam\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 220, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wire2UnisolatedCs\": 24.451,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 221, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"fillerHeight\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 222, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"turnsNoA\": 144,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 223, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"turnsNoB\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 224, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"resistance\": 0.7737,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 225, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"slotCsEff\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 226, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"slotFillFactorTotal\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 227, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"slotFillFactorSection\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 228, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"mainInsulThickness\": 1.3,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 229, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wiresInSeries\": 1,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 230, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wiresSideBySide\": 1,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 231, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wiresStacked1\": 9,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 232, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wiresStacked2\": 9,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 233, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"dummyWire1\": 0,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 234, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"dummyWire2\": 0,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 235, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"boundWireWoMainInsulW\": 10.45,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 236, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"boundWireWoMainInsulH1\": 25.65,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 237, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"boundWireWoMainInsulH2\": 25.65,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 238, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"boundWireWMainInsulW\": 13.05,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 239, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"boundWireWMainInsulH1\": 28.25,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 240, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"boundWireWMainInsulH2\": 28.25,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 241, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"slotTerminationWedge\": \"MAGN\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 242, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wireIsolationTyp\": \"2X70-0,40\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 243, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"isolationTyp\": \"4.35.86\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 244, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"thermalClass\": \"F\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 245, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"connectionDiagramId\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 246, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"conductorsPerSlotCs\": 440.1,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 247, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"overhangAxialLength\": 207,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 248, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"coilDistance\": 5,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 249, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"voltageLevel\": 6600,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 250, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wiuVersion\": \"WiU 6.35.80_0_2009\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 251, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"wireStandardDimension\": \"N\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 252, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"partCoilsNo\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 253, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"bendingRadius\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 254, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"connectionDiagram\": {", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 255, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"id\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 256, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"slotsPerCoilGroupNo\": \"4\",", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 257, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"coilsNo\": 48,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 258, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"polesNoA\": 4,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 259, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"polesNoB\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 260, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"coilGroupInSeriesA\": 4,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 261, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"coilGroupInSeriesB\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 262, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"coilGroupParallelA\": 1,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 263, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"coilGroupParallelB\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 264, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"elecCoilDistance\": 10,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 265, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"pitch\": \"10/12\",", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 266, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"windingFactorA\": 0.925,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 267, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"windingFactorB\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 268, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"slotThrow01\": \"1 11\",", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 269, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"slotThrow02\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 270, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"slotThrow03\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 271, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"slotThrow04\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 272, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"slotThrow05\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 273, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"slotThrow06\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 274, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"slotThrow07\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 275, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"slotThrow08\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 276, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"slotThrow09\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 277, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"slotThrow10\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 278, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"a5eNumber\": \"SB04712\",", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 279, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"numberOfPhases\": 3,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 280, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"numberOfWindingSystems\": 1,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 281, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"specialConnection\": null,", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 282, NodeFullPath = "Tra.BgStatorWinding1.ConnectionDiagram", Line = "                \"status\": null", IsNode = false, Comment = "", Depth = 5 });
        jsonNodes.Add(new JsonNode { Number = 283, NodeFullPath = "Tra.BgStatorWinding1", Line = "            },", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 284, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"id\": 171419,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 285, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"version\": 1,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 286, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"isLastVersion\": true,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 287, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"standardComments\": [],", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 288, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"date\": \"2021-06-17T00:00:00\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 289, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"daisiUseable\": true,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 290, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"username\": \"SYSTEM-IMPORT\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 291, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"comment\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 292, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"standardText\": \"W43:@@;\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 293, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"status\": \"Released\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 294, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"creationTime\": \"2021-09-23T09:50:58.336868\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 295, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"creatorId\": \"Z0049WBV\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 296, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"lastModificationTime\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 297, NodeFullPath = "Tra.BgStatorWinding1", Line = "            \"lastModifierId\": null", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 298, NodeFullPath = "Tra", Line = "        },", IsNode = false, Comment = "", Depth = 2 });
        jsonNodes.Add(new JsonNode { Number = 299, NodeFullPath = "Tra", Line = "        \"bgRotorCage\": {", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 300, NodeFullPath = "Tra.BgRotorCage", Line = "            \"outerCageBarsNo\": 38,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 301, NodeFullPath = "Tra.BgRotorCage", Line = "            \"innerCageBarsNo\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 302, NodeFullPath = "Tra.BgRotorCage", Line = "            \"imdBarsNo\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 303, NodeFullPath = "Tra.BgRotorCage", Line = "            \"outerCageMaterial\": \"E-CU\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 304, NodeFullPath = "Tra.BgRotorCage", Line = "            \"innerCageMaterial\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 305, NodeFullPath = "Tra.BgRotorCage", Line = "            \"slotLining\": \"ST-BLECH\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 306, NodeFullPath = "Tra.BgRotorCage", Line = "            \"designType\": \"VERBINDL\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 307, NodeFullPath = "Tra.BgRotorCage", Line = "            \"outerCageBarLength\": 815,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 308, NodeFullPath = "Tra.BgRotorCage", Line = "            \"innerCageBarLength\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 309, NodeFullPath = "Tra.BgRotorCage", Line = "            \"imdBarLength\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 310, NodeFullPath = "Tra.BgRotorCage", Line = "            \"barShape\": 3,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 311, NodeFullPath = "Tra.BgRotorCage", Line = "            \"outerCageBarDiam\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 312, NodeFullPath = "Tra.BgRotorCage", Line = "            \"outerCageBarW\": 11,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 313, NodeFullPath = "Tra.BgRotorCage", Line = "            \"outerCageBarH\": 32,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 314, NodeFullPath = "Tra.BgRotorCage", Line = "            \"innerCageBarDiam\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 315, NodeFullPath = "Tra.BgRotorCage", Line = "            \"innerCageBarW\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 316, NodeFullPath = "Tra.BgRotorCage", Line = "            \"innerCageBarH\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 317, NodeFullPath = "Tra.BgRotorCage", Line = "            \"outerCageBarCs\": 326,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 318, NodeFullPath = "Tra.BgRotorCage", Line = "            \"innerCageBarCs\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 319, NodeFullPath = "Tra.BgRotorCage", Line = "            \"imdBarCs\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 320, NodeFullPath = "Tra.BgRotorCage", Line = "            \"outerCageBarWeight\": 89.9,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 321, NodeFullPath = "Tra.BgRotorCage", Line = "            \"innerCageBarWeight\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 322, NodeFullPath = "Tra.BgRotorCage", Line = "            \"imdBarWeight\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 323, NodeFullPath = "Tra.BgRotorCage", Line = "            \"outerRingMaterial\": \"SE-CU\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 324, NodeFullPath = "Tra.BgRotorCage", Line = "            \"innerRingMaterial\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 325, NodeFullPath = "Tra.BgRotorCage", Line = "            \"outerRingW\": 25,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 326, NodeFullPath = "Tra.BgRotorCage", Line = "            \"outerRingH\": 50,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 327, NodeFullPath = "Tra.BgRotorCage", Line = "            \"innerRingW\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 328, NodeFullPath = "Tra.BgRotorCage", Line = "            \"innerRingH\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 329, NodeFullPath = "Tra.BgRotorCage", Line = "            \"imdRingW\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 330, NodeFullPath = "Tra.BgRotorCage", Line = "            \"imdRingH\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 331, NodeFullPath = "Tra.BgRotorCage", Line = "            \"outerRingCs\": 1250,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 332, NodeFullPath = "Tra.BgRotorCage", Line = "            \"innerRingCs\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 333, NodeFullPath = "Tra.BgRotorCage", Line = "            \"imdRingCs\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 334, NodeFullPath = "Tra.BgRotorCage", Line = "            \"outerRingWeight\": 21.9,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 335, NodeFullPath = "Tra.BgRotorCage", Line = "            \"innerRingWeight\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 336, NodeFullPath = "Tra.BgRotorCage", Line = "            \"imdRingWeight\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 337, NodeFullPath = "Tra.BgRotorCage", Line = "            \"imdRingMaterial\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 338, NodeFullPath = "Tra.BgRotorCage", Line = "            \"id\": 151855,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 339, NodeFullPath = "Tra.BgRotorCage", Line = "            \"version\": 0,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 340, NodeFullPath = "Tra.BgRotorCage", Line = "            \"isLastVersion\": true,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 341, NodeFullPath = "Tra.BgRotorCage", Line = "            \"standardComments\": [],", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 342, NodeFullPath = "Tra.BgRotorCage", Line = "            \"date\": \"2021-06-17T00:00:00\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 343, NodeFullPath = "Tra.BgRotorCage", Line = "            \"daisiUseable\": true,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 344, NodeFullPath = "Tra.BgRotorCage", Line = "            \"username\": \"SYSTEM-IMPORT\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 345, NodeFullPath = "Tra.BgRotorCage", Line = "            \"comment\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 346, NodeFullPath = "Tra.BgRotorCage", Line = "            \"standardText\": \"X04:@@;                                                          X05:@@;\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 347, NodeFullPath = "Tra.BgRotorCage", Line = "            \"status\": \"Released\",", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 348, NodeFullPath = "Tra.BgRotorCage", Line = "            \"creationTime\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 349, NodeFullPath = "Tra.BgRotorCage", Line = "            \"creatorId\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 350, NodeFullPath = "Tra.BgRotorCage", Line = "            \"lastModificationTime\": null,", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 351, NodeFullPath = "Tra.BgRotorCage", Line = "            \"lastModifierId\": null", IsNode = false, Comment = "", Depth = 4 });
        jsonNodes.Add(new JsonNode { Number = 352, NodeFullPath = "Tra.BgRotorCage", Line = "        },", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 353, NodeFullPath = "Tra.BgRotorCage", Line = "        \"standardComments\": []", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 354, NodeFullPath = "BaseCalculation", Line = "    },", IsNode = false, Comment = "", Depth = 2 });
        jsonNodes.Add(new JsonNode { Number = 355, NodeFullPath = "BaseCalculation", Line = "    \"calculationFactors\": {", IsNode = false, Comment = "", Depth = 2 });
        jsonNodes.Add(new JsonNode { Number = 356, NodeFullPath = "CalculationFactors", Line = "        \"ironFactor\": 1.1,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 357, NodeFullPath = "CalculationFactors", Line = "        \"frictionFactor\": null,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 358, NodeFullPath = "CalculationFactors", Line = "        \"hae1Factor\": 54,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 359, NodeFullPath = "CalculationFactors", Line = "        \"hea2Factor\": 90,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 360, NodeFullPath = "CalculationFactors", Line = "        \"kwFactor\": 1.05,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 361, NodeFullPath = "CalculationFactors", Line = "        \"khFactor\": 1.25,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 362, NodeFullPath = "CalculationFactors", Line = "        \"ksaFactor\": 1,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 363, NodeFullPath = "CalculationFactors", Line = "        \"ksukFactor\": 1,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 364, NodeFullPath = "CalculationFactors", Line = "        \"ks1Factor\": 1,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 365, NodeFullPath = "CalculationFactors", Line = "        \"vaFactor\": 1,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 366, NodeFullPath = "CalculationFactors", Line = "        \"strf\": 0,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 367, NodeFullPath = "CalculationFactors", Line = "        \"statorTemp\": null,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 368, NodeFullPath = "CalculationFactors", Line = "        \"rotorTemp\": 100,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 369, NodeFullPath = "CalculationFactors", Line = "        \"k1\": 0.42,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 370, NodeFullPath = "CalculationFactors", Line = "        \"k2\": 0.35,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 371, NodeFullPath = "CalculationFactors", Line = "        \"k3\": 0.3,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 372, NodeFullPath = "CalculationFactors", Line = "        \"k4\": 0.5,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 373, NodeFullPath = "CalculationFactors", Line = "        \"ReliefOfYoke\": 5", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 374, NodeFullPath = "BaseCalculation", Line = "    },", IsNode = false, Comment = "", Depth = 2 });
        jsonNodes.Add(new JsonNode { Number = 375, NodeFullPath = "BaseCalculation", Line = "    \"coolingSetting\": null,", IsNode = false, Comment = "", Depth = 2 });
        jsonNodes.Add(new JsonNode { Number = 376, NodeFullPath = "BaseCalculation", Line = "    \"ambientCondition\": {", IsNode = false, Comment = "", Depth = 2 });
        jsonNodes.Add(new JsonNode { Number = 377, NodeFullPath = "AmbientCondition", Line = "        \"standardForDetermOfLosses\": \"\",", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 378, NodeFullPath = "AmbientCondition", Line = "        \"addLossesUnloadedMeasured\": \"1\",", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 379, NodeFullPath = "AmbientCondition", Line = "        \"utilisationToTempClass\": \"F*\",", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 380, NodeFullPath = "AmbientCondition", Line = "        \"coolingTemperature\": null,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 381, NodeFullPath = "AmbientCondition", Line = "        \"siteAltitute\": 1", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 382, NodeFullPath = "BaseCalculation", Line = "    },", IsNode = false, Comment = "", Depth = 2 });
        jsonNodes.Add(new JsonNode { Number = 383, NodeFullPath = "BaseCalculation", Line = "    \"operationPoint\": {", IsNode = false, Comment = "", Depth = 2 });
        jsonNodes.Add(new JsonNode { Number = 384, NodeFullPath = "OperationPoint", Line = "        \"machineType\": \"M\",", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 385, NodeFullPath = "OperationPoint", Line = "        \"poleNumberNum\": 5,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 386, NodeFullPath = "OperationPoint", Line = "        \"ratedVoltage\": 6600,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 387, NodeFullPath = "OperationPoint", Line = "        \"connection\": \"Y\",", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 388, NodeFullPath = "OperationPoint", Line = "        \"ratedPowerOutput\": 560,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 389, NodeFullPath = "OperationPoint", Line = "        \"ratedFrequency\": 60,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 390, NodeFullPath = "OperationPoint", Line = "        \"ratioOfStartingTorque\": 2,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 391, NodeFullPath = "OperationPoint", Line = "        \"ratioOfStartingCurrent\": 6.8,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 392, NodeFullPath = "OperationPoint", Line = "        \"ratioOfBreakdownTorque\": 2.8,", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 393, NodeFullPath = "OperationPoint", Line = "        \"usingDefinedValuesForStartup\": false", IsNode = false, Comment = "", Depth = 3 });
        jsonNodes.Add(new JsonNode { Number = 394, NodeFullPath = "BaseCalculation", Line = "    }", IsNode = false, Comment = "", Depth = 2 });
        jsonNodes.Add(new JsonNode { Number = 395, NodeFullPath = "root", Line = "},", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 396, NodeFullPath = "root", Line = "    \"ConductorsSlotNo\": \"5+6\",", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 397, NodeFullPath = "root", Line = "    \"Wire1ParallelNo\": 2,", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 398, NodeFullPath = "root", Line = "    \"WireUnisolatedW\": 4.6,", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 399, NodeFullPath = "root", Line = "    \"WireUnisolatedH\": 2.2,", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 400, NodeFullPath = "root", Line = "    \"OverhangLength\": 0.74,", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 401, NodeFullPath = "root", Line = "    \"MainInsulThickness\": 1.8,", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 402, NodeFullPath = "root", Line = "    \"WiresSideBySide\": 2,", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 403, NodeFullPath = "root", Line = "    \"IsolationTyp\": \"4.35.86\",", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 404, NodeFullPath = "root", Line = "    \"CoilDistance\": 3,", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 405, NodeFullPath = "root", Line = "    \"VoltageLevel\": 6600,", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 406, NodeFullPath = "root", Line = "    \"WiuVersion\": \"WiU 6.35.80_0_2009\",", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 407, NodeFullPath = "root", Line = "    \"WireStandardDimension\": false,", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 408, NodeFullPath = "root", Line = "    \"FillerHeight\": 0.9,", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 409, NodeFullPath = "root", Line = "    \"CoilGroupInSeriesA\": 1,", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 410, NodeFullPath = "root", Line = "    \"CoilGroupParallelA\": 1,", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 411, NodeFullPath = "root", Line = "    \"ElecCoilDistance\": 17,", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 412, NodeFullPath = "root", Line = "    \"OptionalParameters\": true,", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 413, NodeFullPath = "root", Line = "    \"WindingType\": \"LW\",", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 414, NodeFullPath = "root", Line = "    \"FlatWireDimensionsUsage\": true,", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 415, NodeFullPath = "root", Line = "    \"CoilOverhangLengthUsage\": true", IsNode = false, Comment = "", Depth = 1 });
        jsonNodes.Add(new JsonNode { Number = 416, NodeFullPath = "root", Line = "}", IsNode = false, Comment = "", Depth = 1 });
        return jsonNodes;
    }
}